### ISSUE TITLE
[iOS] Error in French "Jump back in"

### ISSUE THREAD

**Issue by dnarcese** [mozilla-l10n/firefoxios-l10n#121]
On the iOS homescreen, it says 'Revenir dans cet onglet' and it should be 'Revenir à cet onglet'.
![image](https://user-images.githubusercontent.com/11432165/143132239-56e8a263-20d9-4808-b5dd-03bebfc75e07.png)

**Comment by dnarcese** [comment]
cc @Delphine

**Comment by Delphine** [comment]
This has been fixed in Pontoon last week, so it should be appearing corrected in the latest l10n import of strings.
Let's double check once that is done. Thanks for flagging!

**Comment by Delphine** [comment]
Closing as this seems resolved! thanks
