### ISSUE TITLE
Fetch localized strings again when a new beta is build

### ISSUE THREAD

**Issue by jakobkappel** [mozilla-l10n/firefoxios-l10n#166]
We have had a few pretty ugly examples of too-long sentences in Danish. The latest is: 

<img width="100" alt="fx_ios_da_welcome_error" src="https://user-images.githubusercontent.com/3586612/194231503-2a035bfd-5be7-40b7-b7e3-150cdf7a3134.png">

(it's hard to tell that the button at the bottom actually is a button, giving the impression that this is something it should be hard to say no to)

--- 

We made a shorter version of the translated string when we saw the above problem in the previous beta version. But since the updated string isn't used in the latest beta or on https://firefox-ci-tc.services.mozilla.com we have no idea if the new string fixes the issue.

Also, updating the beta build (and screenshots) with the latest localized strings gives localizers another chance to fine-tune their translations :)

**Comment by Delphine** [comment]
Thanks for filing Jakob, we were actually talking about this again last week with the Firefox iOS team.
This should ideally be the case. I'll get back in touch once I hear more, many folks are off this week and coming back next week. Cheers!

**Comment by jakobkappel** [comment]
I just installed the newest beta (19965), which uses the new localized string - and it works perfectly \o/

**Comment by Delphine** [comment]
Glad it has worked out! These imports should be more regular from now on :)
