### ISSUE TITLE
Error in Dashboard for telugu locale (te) 

### ISSUE THREAD

**Issue by DineshMv** [mozilla-l10n/firefoxios-l10n#18]
Hello, 
I found an error with firefox for ios project for te locale in the dashboard. I am not sure the reason for it. Dashboard says 
>Error extracting stats: File “Account/Info.plist” is missing target-language attribute.

Please follow this [link](https://l10n.mozilla-community.org/webstatus/?locale=te#xliff_notes) for the details.

**Comment by flodolo** [comment]
It means you need to add a target-language, I assumed Pontoon does, but it looks like it doesn't.

I'm going to fix it.

**Comment by flodolo** [comment]
Fixed in https://github.com/mozilla-l10n/firefoxios-l10n/commit/09627487f5a8780e86739f4eca062b82cdabbe39
